name: flutter_webapi_first_course
description: Projeto do primeiro curso de WebAPI da Formação Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  uuid: ^4.3.3
  google_fonts: ^4.0.4
  http: ^0.13.4
  http_interceptor: ^1.0.2
  logger: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
